apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  labels:
    app: cicd-demo
spec:
  selector:
    matchLabels:
      app: cicd-demo
  replicas: 1
  template:
    metadata:
      name: cicd-demo
      labels:
        app: cicd-demo
    spec:
      containers:
        - name: cicd-demo
          image: local/cicd-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  labels:
    app: cicd-demo
spec:
  type: NodePort
  selector:
    app: cicd-demo
  ports:
    - name: http
      port: 8088
      targetPort: 8088
