apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-assignment1
  labels:
    app: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-assignment1
  template:
    metadata:
      labels:
        app: k8s-assignment1
    spec:
      containers:
        - name: k8s-assignment1
          image: assignment/dockerdemo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
